[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os="none")']
runner = "bootimage runner"

[unstable]
# for memory util function implementations without relying on C lib
build-std-features = ["compiler-builtins-mem"]
# for compiling core for a custom target
build-std = ["core", "compiler_builtins"]
